---
Name: 7days2mod
After: framework/routes#coreroutes
---
Director:
  rules:
    'orgs': 'GitHubRepoController'
    'Data': 'RepoDataController'
    'Mods': 'RepoDataController'
    '$repo/Data': 'RepoDataController'
    '$repo/Mods': 'RepoDataController'
    '$org/$repo/Data': 'RepoDataController'
    '$org/$repo/Mods': 'RepoDataController'
