---
Name: 7days2mod
After: framework/routes#coreroutes
---
Director:
  rules:
    'orgs': 'OrgController'
    'Data': 'DataController'
    'Mods': 'DataController'
    '$repo/Data': 'DataController'
    '$repo/Mods': 'DataController'
    '$org/$repo/Data': 'DataController'
    '$org/$repo/Mods': 'DataController'
